baseURL = "https://grommitstudios.netlify.app/"
languageCode = "en-us"
title = "Grommit Studios"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = " "
    meta_og_title = "Grommit Studios"
    meta_og_type = "website"
    meta_og_url = "https://grommitstudios.netlify.app"
    meta_og_image = "images/header.png"
    meta_og_description = "We're a design and digital product studio focusing on user experience. We make useful and edgy products, like mobile apps, using computers, mood boards, and prototyping."
    meta_twitter_card = "summary"
    meta_twitter_site = "@grommitstudios"
    meta_twitter_creator = "@grommitstudios"

[[menu.main]]
	name = "What we do"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact us"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
